### ISSUE TITLE
Table name as query parameter?

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/asql#15]
I try to perform this:

ASql::APool::database().exec(u"SELECT * FROM $1", {table_name},
                                 [a, c, table_name](ASql::AResult &result) {...}
                                
and in result I got error
ERROR:  syntax error at or near \"$1\"\nLINE 1: SELECT * FROM $1\n

Seems like parameter $1 is not resolved with table_name.
Limitation or bug?

**Comment by cezaryece** [comment]
Of course I can prepare query string like "SELECT * FROM " + table_name and it is working, so it is not big problem...

**Comment by dantti** [comment]
Postgres can not create a plan this way it's impossible to have an optimized query if you don't know the tables, so it doesn't support it.
