### ISSUE TITLE
How to prepare value for column of integer[] type

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/asql#16]
Any QVariant I try to prepare I got query exec errors like
ERROR:  null value in column \"xxx\" violates not-null constraint
or
ERROR:  column \"xxx\" is of type integer[] but expression is of type jsonb

I got values from QJsonObject where data for int[] columnt is in QJsonArray and I ahve only problem with this column.
How I must prepare QVariant from QJsonArray so it fit integer[] format?

**Comment by dantti** [comment]
This seems like two questions, for which the second I don't know how to convert arrays to something postgres can undestand like integer[], so what I do is pass as string` $1::integer[] -> "{123,456}"`
For the first might be related to the array not being able to convert to an array.

**Comment by cezaryece** [comment]
There is also problem with text[] column type.
When I prepare value by QStringList list = val.toVariant().toStringList();
I got 
Failed to add new actor:ERROR:  malformed array literal: \"1\"\nDETAIL:  Array value must start with \"{\" or dimension information.\n"

**Comment by dantti** [comment]
Yes, it's the same issue, array typed columns are not supported, not sure it's possible to send their binary representation over the wire, so if you manage to do so please do PR.

**Comment by dantti** [comment]
And again you can still cast a string to text tho it might need some escaping `$1::text[] -> "{'foo','bar'}"`
