### ISSUE TITLE
query with integer[] array

### ISSUE THREAD

**Issue by frankipl** [cutelyst/asql#17]
Hi
We are trying to use Cutelyst in web projects. So far I have been using [QHttpEngine](https://github.com/nitroshare/qhttpengine) in Qt servers and would like to switch to Cutelyst with ASql library, so first of all: 
Thank You for your work.

I'm trying to make a query which inserts into a table where column is int array
```
      Table "public.test"
 Column |   Type    | Modifiers 
--------+-----------+-----------
 a      | integer[] | 
```

So query would be: 
insert into test (a) values ('{1,2}');

And I'm trying with code:
```
    QString queryStr = QStringLiteral("insert into test (a) values ($1)")
    QList<QVariant> role;
    role <<QVariant(3)<<QVariant(4);
    QVariantList myList;
    myList << QVariant(role);
    qDebug()<<"myList: "<<myList;

    ASql::APool::database().exec(queryStr,myList, [=] (ASql::AResult &result) {
```
it gives output:
```
myList:  (QVariant(QVariantList, (QVariant(int, 3), QVariant(int, 4))))
LOG:  execute <unnamed>: insert into test (a) values ($1)
DETAIL:  parameters: $1 = NULL
```

So the parameter is always NULL, we have tried different options... , how to setup myList for this ?

Best Regards
Marek

**Comment by dantti** [comment]
This is similar to the question in #15 , I don't know what DB library that you have used before but I don't know how to serialize the list of int in binary form so that PG understands it, so the only way to do this is by using strings, and that's what I do.

`db.exec(u"insert into test (a) values ($1::integer[])",{ QStringLiteral("{1,2}") }, [=] (AResult &result) {`

**Comment by dantti** [comment]
It seems it could be possible to do this with some QList<int> 
https://stackoverflow.com/questions/4016412/postgresqls-libpq-encoding-for-binary-transport-of-array-data
but I don't have time to look into this, so a PR is welcome :)

**Comment by cezaryece** [comment]
@frankipl I think you can close this issue as solved by preparing literal accepted by PostgreSQL.

**Comment by frankipl** [comment]
yes of course, sorry for the delay.
