### ISSUE TITLE
Using ASql with sync mode?

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/asql#18]
Is there any possibility to use ASql in sync mode?
Why? Because I would like to have simple queries return result immediately to my code, so I can use it as return value of function.
So... can I achieve this with ASql or I must to use standard QSql class and mix it with ASql usage?

**Comment by dantti** [comment]
No, it was designed around async, any query can still block your process if they go to a busy server or if you have some simple queries or if you have some network issue. If you really want blocking then use QtSql or some other sync lib.
