### ISSUE TITLE
Feature Request: ad field like QSqlQuery ASql::AResult::lastExecutedQuery

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/asql#19]
It would be useful to have in ASql::AResult access to last executed query.
If I have multiple queries send in one ASql::APool::database().exec then when I check each result I cant get query which caused error.
Sometimes result.errorString() is not enough...
If you think QSqlQuery is too big object to add it to ASql::AResult (or for other reasons) then at least you can add just executed query string.

**Comment by dantti** [comment]
There's no such thing as QSqlQuery in ASql as it doesn't depend on QtSql and won't.
You can easily overcome this by creating a QString outside the lambda and then capturing it, but I'll think about exposing the QByteArray sent to the DB.

**Comment by cezaryece** [comment]
If it will be convertible to QString (or something human-readable) with query then fine.
Or at least can you expose index of query in queries list?
Something I can recognize what query was failed;

**Comment by dantti** [comment]
In Postgres it's converted to UTF-8 so you would QString::fromUtf8(), not sure future drivers would also be utf-8, and due string views I don't store a QString to avoid another allocation.
