### ISSUE TITLE
db.exec on a disconnected database 

### ISSUE THREAD

**Issue by vingeni** [cutelyst/asql#21]
Hi,

When my cutelyst instance has some database troubles, the coming requests looks "stalled" somewhere.

Even when the database connection is established after all, the previous pending requests are not executed.

Is there a way to handle database states with asql to avoid this behavior ?

Step to reproduce :
- start a sample cutelyst application
- make a request (which should be fine!)
- disconnect the database (e.g: /etc/init.d/postgres stop)
- make a request
- the cutelyst application is stalled
- restore the database (e.g: /etc/init.d/postgres start)
- the request is still on hold.

Here is my sample controller :
```
void test::index(Context *c)
{
    auto db = APool::database();
    ASync a(c);

    db.exec("select now()",
            {},
            [a, c] (AResult &result) {
                if (result.error()) {
                    c->response()->body() = result.errorString().toUtf8();
                    c->response()->setStatus(500);
                }
                c->response()->body() = result[0][0].toString().toUtf8();
            });
}
```
I would expect ;
- having result.error() triggered when database is not available ,
- or having an executed request if the database state is changed to "Connected"

**Comment by dantti** [comment]
If you use latest master all queries are going to have an error result if the database disconnects. I think I fixed this yesterday.

**Comment by dantti** [comment]
Also note that your code could crash as you didn't pass a receiver QObject to exec(), and I changed the API so that now you must pass it (or nullptr if you are sure it won't have a dangling pointer like *c)
