### ISSUE TITLE
Feature Request: more detailed info for multiqueries

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/asql#22]
If I post multiple queries in one string I dont get any information which one is executed, which one cause error etc.
At least I want to get index of current query I can identify which one is current from my list.

**Comment by dantti** [comment]
It's easy to add a counter to client code, not sure I want to add this

**Comment by cezaryece** [comment]
I dont know how I can get any query counter in lambda expression handler on each query result.
I have checked that on each call of lambda I got whole query string /"SELECT...; SELECT...; SELECT....; SELECT...; SELECT.../  in query(), not only for query just executed (mean one "SELECT...") 
In fact that it would be very sufficient for me.

**Comment by dantti** [comment]
ASql just sends the whole string to the server, and the server doesn't reply which query it run.
auto counter = std::make_shared<int>(0);
[counter]()....
should be enough, you can also use pipeline mode instead of having a big query.

**Comment by cezaryece** [comment]
Yes, it is working, THX
