### ISSUE TITLE
HELP needed: transaction when calling many functions with queries

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/asql#27]
I have quite complicated routines in my Cutelyst/Asql based application.
In few places there is stream of calls like this:
ASql::APool::database().exec(....,[=]((ASql::AResult &result){
   if (!result.error()) {
        ....
       SomeNextFunction(c, result, [=](Context *c, QJsonArray res) {
           ....
       });
   }
}
When you surround this with **ATransaction t** it is easy to pass **t** as lambda parameter.
But if SomeNextFunction contains inside another call of ASql::APool::database().exec (prepend by Async a(c)) it seems transaction is not rolling back changes made by SomeNextFunction.

Is there any way to rolling back all queries automatically?
Am I doing this wrong way?

**Comment by dantti** [comment]
Transaction works per DB connection, APool gives you another db connection, so yes, either pass the db object or use t.database()
