### ISSUE TITLE
0.92 release doesn't compile (FreeBSD, clang)

### ISSUE THREAD

**Issue by adriaandegroot** [cutelyst/asql#34]
Building cutelyst-asql 0.92 release tarball on FreeBSD, with clang 17, first fails like this:

```
In file included from /wrkdirs/usr/ports/databases/cutelyst-asql/work/asql-0.92.0/src/apool.cpp:8:
/wrkdirs/usr/ports/databases/cutelyst-asql/work/asql-0.92.0/src/acoroexpected.h:46:32: error: invalid use of incomplete type 'ATransaction'
   46 |                     m_result = ATransaction(database, true);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/databases/cutelyst-asql/work/asql-0.92.0/src/adatabase.h:18:7: note: forward declaration of 'ASql::ATransaction'
   18 | class ATransaction;
```

Which, yeah, there is a missing include there -- maybe you never instantiate this template? Clang is kind of picky about these things. After adding `#include <atransaction.h>` to the `adatabase.h` header, the build fails in a different way:

```
In file included from /wrkdirs/usr/ports/databases/cutelyst-asql/work/asql-0.92.0/src/acache.cpp:8:
/wrkdirs/usr/ports/databases/cutelyst-asql/work/asql-0.92.0/src/acoroexpected.h:47:32: error: calling a protected constructor of class 'ASql::ATransaction'
   47 |                     m_result = ATransaction(database, true);
      |                                ^
/wrkdirs/usr/ports/databases/cutelyst-asql/work/asql-0.92.0/src/acoroexpected.h:42:20: note: while substituting into a lambda expression here
   42 |         callback = [this](AResult &result) {
/wrkdirs/usr/ports/databases/cutelyst-asql/work/asql-0.92.0/src/acache.cpp:255:21: note: in instantiation of member function 'ASql::ACoroExpected<ASql::AResult>::ACoroExpected' requested here
  255 |     AExpectedResult coro(receiver);
```

This makes some sense: this template instantiation isn't the friend instantiation declared in `ATransaction`. This might be clang being overly-agressive in instantiating / checking templates. You might be able to use a `requires` (e.g. that the template `T` is `ATransaction`) to suppress instantiation in other contexts.

**Comment by adriaandegroot** [comment]
Er .. that expression is in an `if constexpr()` block which checks exactly what I suggest, so I'm not sure what clang is thinking here.

**Comment by dantti** [comment]
hmm I pushed a change that might help, tho dunno how well is coroutines clang support, it failed to build here

**Comment by dantti** [comment]
I've added CI https://github.com/cutelyst/asql/pull/35 builds fine on gcc/clang/msvc

**Comment by adriaandegroot** [comment]
[acoroexpected.txt](https://github.com/user-attachments/files/17708681/acoroexpected.txt)

I ended up with this patch, which I don't think is upstreamable at all -- it uses concepts / `requires` to lift the `if constexpr()` right outside the function. This seems like a clang issue, but I don't have time to investigate further. It builds, I can package it :)

**Comment by dantti** [comment]
I got this error with clang-18 because it was trying to using libstd++, I pushed a patch to force it to use libc++, not sure it's the best thing, on macOS I guess it works as there is no libstd++ by default there, as I plan to remove the lambdas interface once all my projects use the coroutines API it's a bit important to have this working :)
