### ISSUE TITLE
Suspicious ")", "tabsle" and more

### ISSUE THREAD

**Issue by Ganton** [cutelyst/asql#4]
Hello. If I were you I would look at the examples seen on https://github.com/cutelyst/asql/ because there are some suspicious ")" : 
    - db.exec("SELECT id, message FROM messages LIMIT 5"), [=] [...]
    - db.exec("SELECT pg_sleep(5)"), [=] [...]
    - possibly more
and some "tabsle".

I suppose that more little bugs will exists, because I really haven't tested the code, just skimmed it. And I wanted to thank you for Asql :-)

**Comment by dantti** [comment]
Fixed thanks
