### ISSUE TITLE
Executable names with Qt5 and Qt6

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/asql#5]
I open this issue only here, because I will start with _asql_ as it is smaller than _cutelyst_, but issue is the same. :)

Now that there is / will be support for two versions of Qt it would be nice to have the used version of Qt in the executable names, too. Otherwise one would have file conflicts with having packages installed for both versions of Qt. So, e.g. for _asql_ there is the `asql-migration` executable. My proposal would be to add a Qt version suffix like `-qt5` and `-qt6`. Same would than have to be done for the cutelyst executables.

I could for sure also only patch my distribution packages but would be then out of line with the upstream naming. :)

**Comment by dantti** [comment]
yeah, I couldn't think of a better way to deal with this, only perhaps using some env var line qtconfig used to do.
